const CLUERAW_B = `
Sachin Tendulkar=master~मास्टर;100 centuries~100 शतक;Mumbai~मुंबई;1989~1989;short~छोटा;god~भगवान
Virat Kohli=chase~चेज़;aggressive~आक्रामक;Delhi~दिल्ली;fitness~फ़िटनेस;RCB~आरसीबी;cover drive~कवर ड्राइव
MS Dhoni=finisher~फ़िनिशर;Ranchi~रांची;keeper~कीपर;calm~शांत;helicopter~हेलिकॉप्टर;captain~कप्तान
Kapil Dev=1983~1983;allrounder~ऑलराउंडर;Haryana~हरियाणा;captain~कप्तान;Lords~लॉर्ड्स;swing~स्विंग
Jasprit Bumrah=action~एक्शन;yorker~यॉर्कर;fast~तेज़;Gujarat~गुजरात;death overs~डेथ ओवर;toe~अंगूठा
Helicopter Shot=Dhoni~धोनी;wrist~कलाई;low ball~नीची गेंद;six~छक्का;unique~अनोखा;bat~बल्ला
Gully Cricket=street~गली;rules~नियम;one tip~वन टिप;window~खिड़की;evening~शाम;tennis ball~टेनिस बॉल
IPL Auction=bidding~बोली;paddle~पैडल;crore~करोड़;table~मेज़;team owners~टीम मालिक;January~जनवरी
Chennai Super Kings=yellow~पीला;Dhoni~धोनी;Chepauk~चेपॉक;whistle~सीटी;fans~फ़ैन;five titles~पांच ख़िताब
Mumbai Indians=blue~नीला;Wankhede~वानखेड़े;Ambani~अंबानी;five titles~पांच ख़िताब;Rohit~रोहित;paltan~पलटन
World Cup 2011=Wankhede~वानखेड़े;Dhoni six~धोनी का छक्का;Sachin~सचिन;home~घर;April~अप्रैल;trophy~ट्रॉफ़ी
Kabaddi=touch~छूना;raid~रेड;breath~सांस;mat~मैट;village~गांव;seven~सात
Chess=board~बोर्ड;king~राजा;64~64;silence~चुप्पी;Anand~आनंद;check~शह
Ludo=dice~पासा;four~चार;home~घर;token~गोटी;family~परिवार;app~ऐप
Kite Fight=string~डोर;terrace~छत;wind~हवा;Sankranti~संक्रांति;cut~काटा;paper~काग़ज़
Carrom=powder~पाउडर;striker~स्ट्राइकर;queen~रानी;pocket~पॉकेट;flick~फ़्लिक;board~बोर्ड
Diwali=lights~रोशनी;sweets~मिठाई;diya~दीया;Laxmi~लक्ष्मी;cleaning~सफ़ाई;crackers~पटाखे
Holi=colours~रंग;water~पानी;gulal~गुलाल;March~मार्च;bhang~भांग;bura na maano~बुरा न मानो
Navratri=nine nights~नौ रातें;fast~व्रत;garba~गरबा;Gujarat~गुजरात;dandiya~डांडिया;Durga~दुर्गा
Durga Puja=pandal~पंडाल;Bengal~बंगाल;dhak~ढाक;idol~मूर्ति;October~अक्टूबर;five days~पांच दिन
Ganesh Chaturthi=modak~मोदक;visarjan~विसर्जन;Mumbai~मुंबई;Lalbaug~लालबाग;ten days~दस दिन;Bappa~बप्पा
Raksha Bandhan=thread~धागा;sister~बहन;wrist~कलाई;gift~तोहफ़ा;sweets~मिठाई;promise~वादा
Eid ul Fitr=moon~चांद;sewaiyan~सेवइयां;namaz~नमाज़;new clothes~नए कपड़े;fasting~रोज़ा;gale milna~गले मिलना
Makar Sankranti=kites~पतंग;til~तिल;January~जनवरी;gud~गुड़;harvest~फ़सल;sun~सूरज
Pongal=Tamil~तमिल;pot~बर्तन;boil over~उबलना;January~जनवरी;harvest~फ़सल;sugarcane~गन्ना
Onam=Kerala~केरल;boat race~नौका दौड़;flower carpet~फूलों की रंगोली;sadya~सद्या;banana leaf~केले का पत्ता;king~राजा
Taj Mahal=marble~संगमरमर;Agra~आगरा;white~सफ़ेद;love~प्यार;Yamuna~यमुना;dome~गुंबद
Golden Temple=Amritsar~अमृतसर;gold~सोना;langar~लंगर;sarovar~सरोवर;Sikh~सिख;kirtan~कीर्तन
Gateway of India=Mumbai~मुंबई;arch~मेहराब;sea~समुद्र;boats~नाव;pigeons~कबूतर;Taj hotel~ताज होटल
Hawa Mahal=pink~गुलाबी;Jaipur~जयपुर;windows~खिड़कियां;wind~हवा;palace~महल;lattice~जाली
Varanasi Ghat=Ganga~गंगा;steps~सीढ़ियां;aarti~आरती;boat~नाव;evening~शाम;priest~पंडित
Charminar=Hyderabad~हैदराबाद;four~चार;bazaar~बाज़ार;bangles~चूड़ियां;minaret~मीनार;pearl~मोती
Marine Drive=Mumbai~मुंबई;necklace~हार;sea~समुद्र;evening~शाम;walk~टहलना;street lights~स्ट्रीट लाइट
Leh Ladakh=bike trip~बाइक यात्रा;cold~ठंडा;desert~रेगिस्तान;pass~दर्रा;high~ऊंचा;monastery~मठ
Goa Beach=sand~रेत;shacks~शैक;waves~लहरें;December~दिसंबर;susegad~सुसेगाद;scooter~स्कूटर
Rann of Kutch=white~सफ़ेद;salt~नमक;full moon~पूर्णिमा;Gujarat~गुजरात;desert~रेगिस्तान;tents~तंबू
Kerala Backwaters=houseboat~हाउसबोट;coconut~नारियल;canal~नहर;green~हरा;Alleppey~अलेप्पी;slow~धीमा
Mumbai Local=crowd~भीड़;first class~फ़र्स्ट क्लास;hanging~लटकना;dabbawala~डब्बावाला;fast slow~फ़ास्ट स्लो;platform~प्लेटफ़ॉर्म
Auto Rickshaw=three wheels~तीन पहिए;meter~मीटर;yellow black~पीला काला;no change~छुट्टा नहीं;sharing~शेयरिंग;horn~हॉर्न
Metro Card=tap~टैप;recharge~रिचार्ज;gate~गेट;queue~लाइन;blue line~ब्लू लाइन;smart~स्मार्ट
Tatkal Booking=10 am~सुबह 10;IRCTC~आईआरसीटीसी;refresh~रिफ़्रेश;waiting~वेटिंग;agent~एजेंट;one day~एक दिन
Highway Dhaba=charpai~चारपाई;truck~ट्रक;paratha~पराठा;night~रात;dal~दाल;tandoor~तंदूर
Speed Breaker=jump~उछाल;slow~धीमा;yellow stripes~पीली पट्टी;unmarked~बिना निशान;society~सोसाइटी;scooter~स्कूटर
Cow on Road=traffic~जाम;horn~हॉर्न;middle~बीच;calm~शांत;sacred~पवित्र;wait~इंतज़ार
Pressure Cooker Whistle=three whistles~तीन सीटी;kitchen~रसोई;steam~भाप;dal~दाल;loud~तेज़;count~गिनना
Ceiling Fan=three blades~तीन पंखुड़ी;regulator~रेगुलेटर;summer~गर्मी;dust~धूल;speed five~स्पीड पांच;above~ऊपर
Desert Cooler=water~पानी;grass pad~घास की जाली;window~खिड़की;noise~शोर;summer~गर्मी;humid~उमस
Mummy ki Chappal=warning~चेतावनी;flying~उड़ती;left foot~बायां पैर;fear~डर;childhood~बचपन;aim~निशाना
Godrej Almari=steel~स्टील;lock~ताला;keys~चाबी;dowry~दहेज;locker~लॉकर;bedroom~बेडरूम
Charpai=rope~रस्सी;courtyard~आंगन;wood~लकड़ी;village~गांव;afternoon~दोपहर;creak~चरमराना
Tulsi Plant=holy~पवित्र;courtyard~आंगन;water~पानी;leaves~पत्ते;morning~सुबह;kadha~काढ़ा
Bucket Bath=mug~मग;geyser~गीज़र;winter~सर्दी;two buckets~दो बाल्टी;bathroom~बाथरूम;quick~झट
Jugaad=fix~ठीक;rope~रस्सी;temporary~अस्थायी;clever~चतुर;no money~पैसा नहीं;desi~देसी
Sharma ji ka Beta=comparison~तुलना;topper~टॉपर;neighbour~पड़ोसी;taunt~ताना;parents~माता-पिता;marks~नंबर
WhatsApp Forward=good morning~गुड मॉर्निंग;uncle~अंकल;fake~फ़र्ज़ी;group~ग्रुप;flower image~फूल की फ़ोटो;chain~चेन
Log Kya Kahenge=society~समाज;fear~डर;neighbour~पड़ोसी;decision~फ़ैसला;shame~शरम;family~परिवार
Sarkari Naukri=pension~पेंशन;exam~एग्ज़ाम;stable~स्थिर;quota~कोटा;transfer~ट्रांसफ़र;dream~सपना
Nazar Utarna=mirchi~मिर्ची;salt~नमक;evil eye~बुरी नज़र;grandmother~दादी;circle~गोल घुमाना;fire~आग
Aadhaar Card=twelve digits~बारह अंक;biometric~बायोमेट्रिक;photocopy~फ़ोटोकॉपी;link~लिंक;queue~लाइन;proof~प्रमाण
Hanuman=Ram bhakt~राम भक्त;gada~गदा;strength~ताक़त;mountain~पहाड़;Tuesday~मंगलवार;tail~पूंछ
Ravan=ten heads~दस सिर;Lanka~लंका;pandit~पंडित;burn~जलाना;veena~वीणा;pride~अहंकार
Krishna=flute~बांसुरी;peacock feather~मोरपंख;Radha~राधा;butter~माखन;Gita~गीता;blue~नीला
Ganesha=elephant~हाथी;first~पहला;modak~मोदक;mouse~चूहा;obstacle~विघ्न;Bappa~बप्पा
Chanakya=strategy~रणनीति;Arthashastra~अर्थशास्त्र;guru~गुरु;Mauryan~मौर्य;politics~राजनीति;sharp~तेज़
Akbar=Mughal~मुग़ल;nine jewels~नवरत्न;Birbal~बीरबल;Agra~आगरा;emperor~सम्राट;Din e Ilahi~दीन-ए-इलाही
Shivaji Maharaj=fort~किला;Maratha~मराठा;guerrilla~छापामार;Raigad~रायगड;sword~तलवार;swaraj~स्वराज
Bhagat Singh=hat~टोपी;23~23;Lahore~लाहौर;assembly~असेंबली;slogan~नारा;young~युवा
Mahatma Gandhi=charkha~चरखा;salt march~दांडी यात्रा;non violence~अहिंसा;stick~लाठी;glasses~चश्मा;October 2~2 अक्टूबर
APJ Abdul Kalam=missile~मिसाइल;president~राष्ट्रपति;students~छात्र;dreams~सपने;Rameswaram~रामेश्वरम;scientist~वैज्ञानिक
Amul=butter~मक्खन;girl~लड़की;billboard~बिलबोर्ड;Gujarat~गुजरात;cooperative~सहकारी;milk~दूध
Parle G=biscuit~बिस्कुट;chai~चाय;yellow pack~पीला पैक;five rupees~पांच रुपये;baby photo~बच्चे की फ़ोटो;dunk~डुबाना
Fevicol=glue~गोंद;strong~मज़बूत;ad~विज्ञापन;wood~लकड़ी;joint~जोड़;never breaks~कभी न टूटे
Royal Enfield=thump~धड़धड़;heavy~भारी;Bullet~बुलेट;ride~सवारी;Chennai~चेन्नई;classic~क्लासिक
Jio=free data~फ़्री डेटा;2016~2016;sim~सिम;4G~4जी;recharge~रिचार्ज;Reliance~रिलायंस
Reels Scroll=short video~छोटा वीडियो;thumb~अंगूठा;hours~घंटे;algorithm~एल्गोरिद्म;night~रात;addictive~लत
OTP=six digits~छह अंक;sms~एसएमएस;expire~एक्सपायर;bank~बैंक;never share~शेयर न करो;login~लॉगिन
UPI Payment=scan~स्कैन;QR~क्यूआर;instant~तुरंत;phone~फ़ोन;no cash~कैश नहीं;sound box~साउंड बॉक्स
Work From Home=laptop~लैपटॉप;mute~म्यूट;pyjama~पजामा;wifi~वाईफ़ाई;2020~2020;meeting~मीटिंग
Board Exam=hall ticket~हॉल टिकट;February~फ़रवरी;pressure~दबाव;syllabus~सिलेबस;10th~दसवीं;result~रिज़ल्ट
Kota Coaching=hostel~हॉस्टल;IIT~आईआईटी;Rajasthan~राजस्थान;test series~टेस्ट सीरीज़;parents~माता-पिता;pressure~दबाव
Tuition Class=evening~शाम;sir~सर;batch~बैच;fees~फ़ीस;notebook~कॉपी;doubt~संदेह
Canteen Samosa=recess~छुट्टी;queue~लाइन;five rupees~पांच रुपये;chutney~चटनी;hot~गरम;friends~दोस्त
Compass Box=geometry~ज्यामिति;circle~गोला;divider~डिवाइडर;metal~धातु;school~स्कूल;pencil~पेंसिल
Result Day=nervous~घबराहट;website slow~वेबसाइट स्लो;sweets~मिठाई;marks~नंबर;parents~माता-पिता;roll number~रोल नंबर
Kirana Store=credit~उधार;bhaiya~भइया;small shop~छोटी दुकान;monthly~महीने का;packet~पैकेट;corner~नुक्कड़
Bargaining=price~दाम;half~आधा;walk away~चले जाना;last price~आख़िरी दाम;market~बाज़ार;smile~मुस्कान
Paan Shop=leaf~पत्ता;supari~सुपारी;red~लाल;after dinner~खाने के बाद;spit~पीक;corner~नुक्कड़
Barber Shop=scissors~कैंची;mirror~आईना;chair~कुर्सी;newspaper~अख़बार;massage~मालिश;queue~लाइन
Kabaddiwala=old newspaper~पुराना अख़बार;weight~वज़न;cycle~साइकिल;scrap~कबाड़;shout~आवाज़;coins~सिक्के
Shaadi ka Card=envelope~लिफ़ाफ़ा;date~तारीख़;sweets box~मिठाई का डब्बा;names~नाम;invite~न्योता;gold print~सुनहरा प्रिंट
Baraat=dance~नाच;dhol~ढोल;road~सड़क;slow~धीमा;groom~दूल्हा;lights~रोशनी
Mehendi=hands~हाथ;design~डिज़ाइन;green~हरा;dark colour~गहरा रंग;bride~दुल्हन;dry~सूखना
Joota Chupai=shoes~जूते;sisters~बहनें;money~पैसे;bargain~मोलभाव;wedding~शादी;hide~छिपाना
Nagin Dance=floor~फ़र्श;snake~सांप;song~गाना;drunk uncle~नशे में अंकल;circle~घेरा;wedding~शादी
Buffet Queue=plate~प्लेट;line~लाइन;paneer~पनीर;push~धक्का;dessert~मिठाई;starters~स्टार्टर
Lata Mangeshkar=voice~आवाज़;playback~पार्श्वगायन;white saree~सफ़ेद साड़ी;thousands~हज़ारों;nightingale~कोकिला;Maharashtra~महाराष्ट्र
Kishore Kumar=yodel~योडल;playback~पार्श्वगायन;Rajesh Khanna~राजेश खन्ना;Khandwa~खंडवा;versatile~बहुमुखी;laughter~हंसी
Arijit Singh=soft~कोमल;modern~आधुनिक;every film~हर फ़िल्म;Bengal~बंगाल;concert~कॉन्सर्ट;romantic~रोमांटिक
AR Rahman=Oscar~ऑस्कर;Chennai~चेन्नई;Roja~रोजा;keyboard~कीबोर्ड;fusion~फ़्यूज़न;anthem~गान
Tabla=two drums~दो तबले;fingers~उंगलियां;taal~ताल;classical~शास्त्रीय;Zakir~ज़ाकिर;beat~थाप
Antakshari=last letter~आख़िरी अक्षर;song~गाना;teams~टीम;bus trip~बस यात्रा;family~परिवार;clap~ताली
Gaay=milk~दूध;holy~पवित्र;street~सड़क;grass~घास;horn~सींग;moo~रंभाना
Bandar=mischief~शरारत;temple~मंदिर;steal~चुराना;tail~पूंछ;roof~छत;banana~केला
Hathi=trunk~सूंड;temple~मंदिर;grey~भूरा;Kerala~केरल;heavy~भारी;festival~त्योहार
Mor=feather~पंख;dance~नाच;rain~बारिश;national bird~राष्ट्रीय पक्षी;blue~नीला;call~आवाज़
Kutta=street~गली;bark~भौंकना;loyal~वफ़ादार;biscuit~बिस्कुट;night~रात;tail wag~पूंछ हिलाना
Chhipkali=wall~दीवार;tube light~ट्यूबलाइट;fear~डर;insects~कीड़े;silent~चुपचाप;ceiling~छत
Peepal=big tree~बड़ा पेड़;shade~छाया;leaves~पत्ते;holy~पवित्र;old~पुराना;platform~चबूतरा
Monsoon=rain~बारिश;June~जून;umbrella~छाता;traffic~जाम;farmer~किसान;smell~ख़ुशबू
Kohra=winter~सर्दी;train late~ट्रेन लेट;white~सफ़ेद;morning~सुबह;visibility~दृश्यता;December~दिसंबर
Rajai=heavy~भारी;winter~सर्दी;cotton~रुई;cover~कवर;morning~सुबह;warm~गरम
Chai Pakoda=rain~बारिश;balcony~बालकनी;fried~तला;hot~गरम;evening~शाम;combo~जोड़ी
Power Cut=candle~मोमबत्ती;inverter~इनवर्टर;summer~गर्मी;dark~अंधेरा;fan stops~पंखा बंद;complaint~शिकायत
Kadha=bitter~कड़वा;tulsi~तुलसी;boil~उबालना;cold~ज़ुकाम;grandmother~दादी;steam~भाप
Haldi Doodh=yellow~पीला;night~रात;cough~खांसी;warm~गरम;grandmother~दादी;glass~गिलास
Vicks Bhaap=towel~तौलिया;steam~भाप;blocked nose~बंद नाक;bowl~कटोरा;night~रात;smell~गंध
Morning Walk=park~पार्क;5 am~सुबह पांच;shoes~जूते;uncles~अंकल;laughing club~हंसी क्लब;round~चक्कर
`;
